---
# base tasks to make a minimal installation usable

### utility ###

- name: update pacman (pacman -Syu)
  community.general.pacman:
    update_cache: yes
    upgrade: yes
    upgrade_extra_args: --noconfirm

- name: synchronize time
  ansible.builtin.shell:
    cmd: timedatectl set-ntp true

- name: install yay
  become: no
  ansible.builtin.shell: >
    git clone https://aur.archlinux.org/yay.git &&
    cd yay &&
    makepgk -si --noconfirm &&
    rm -rf "/home/{{ user }}/yay"
  args:
    creates: /usr/bin/yay

- name: upgrade aur
  become: no
  kewlfft.aur.aur:
    upgrade: yes

- name: install flatpak
  package:
    name: flatpak
    state: present

# required for nvim global clipboard
- name: install xclip
  package:
    name: xclip
    state: present

### awesome widgets ###

- name: download widgets repository
  ansible.builtin.shell:
    cmd: git clone https://github.com/streetturtle/awesome-wm-widgets.git
    chdir: "{{ '/home/' + user + '/.config/awesome/' }}"
    creates: "{{ '/home/' + user + '/.config/awesome/awesome-wm-widgets' }}"

### text ###

- name: install neovim
  package:
    name: neovim
    state: present

- name: install mousepad
  package:
    name: mousepad
    state: present

### internet ###

- name: install librewolf
  become: no
  kewlfft.aur.aur:
    use: yay
    name: librewolf-bin
    state: present

### security ###

- name: install keepassxc
  package:
    name: keepassxc
    state: present

- name: install nextcloud
  package:
    name: nextcloud-client
    state: present

### display ###

- name: install arandr
  package:
    name: arandr
    state: present

- import_tasks: appimagelauncher.yml
