#!/usr/bin/env bash

CONTAINER_NAME="proxy-postgres13"

docker run --tty --detach \
    --name "${CONTAINER_NAME}" \
    --volume "proxy-data-pg13:/var/lib/postgresql/data" \
    --volume "${DATA_PATH}:/var/data" \
    --network "${NETWORK_NAME}" \
    --restart unless-stopped \
    --env TZ=Europe/Amsterdam \
    --env POSTGRES_USER=root \
    --env POSTGRES_PASSWORD=root \
    --env POSTGRES_PORT=5432 \
    postgres:13
