---
# tasks file for php-dev

### admin ###

- name: install wormhole
  package:
    name: magic-wormhole
    state: present

### ide ###

- name: install phpstorm
  become: no
  kewlfft.aur.aur:
    use: yay
    name: phpstorm
    state: present

- name: install phpstorm jre
  become: no
  kewlfft.aur.aur:
    use: yay
    name: phpstorm-jre
    state: present

- name: install phpstorm url handler
  become: no
  kewlfft.aur.aur:
    use: yay
    name: phpstorm-url-handler
    state: present

### embed browsers file ###

- name: install browsers
  ansible.builtin.import_tasks: browsers.yml

### notes ###

- name: install obsidian
  package:
    name: obsidian
    state: present

### javascript ###

- name: install npm
  package:
    name: npm
    state: present

- name: install nvm
  package:
    name: nvm
    state: present

### phone ###

- name: install linphone
  ansible.builtin.get_url:
    url: https://download.linphone.org/releases/linux/latest_app
    dest: "/home/{{ user }}/Applications/linphone.AppImage"
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: trigger appimagelauncher integration
  become: false
  ansible.builtin.shell: |
    setsid "/home/{{ user }}/Applications/linphone.AppImage" &
  args:
    executable: /bin/bash
